Update sync-packages.yml

diff --git a/.github/workflows/sync-packages.yml b/.github/workflows/sync-packages.yml
--- a/.github/workflows/sync-packages.yml
+++ b/.github/workflows/sync-packages.yml
@@ -402,6 +402,24 @@ jobs:
           echo "GCC_DIR = $GCC_DIR"
           ls -l "$GCC_DIR"
           export GCC_EXEC_PREFIX="$TIZEN_SDK/tools/data/tools/arm-linux-gnueabi-gcc-4.9/"
+          echo "🔧 Creating GCC cc1 / cc1plus symlinks"
+          mkdir -p "$GCC_EXEC_PREFIX/arm-linux-gnueabi/4.9.2"
+
+          REAL_CC1="$GCC_EXEC_PREFIX/libexec/gcc/arm-linux-gnueabi/4.9.2/cc1"
+          if [[ ! -f "$REAL_CC1" ]]; then
+              echo "❌ REAL cc1 not found — toolchain layout different!"
+              find "$GCC_EXEC_PREFIX" -name cc1 -maxdepth 5
+              exit 1
+          fi
+          
+          ln -sf \
+            "$GCC_EXEC_PREFIX/libexec/gcc/arm-linux-gnueabi/4.9.2/cc1" \
+            "$GCC_EXEC_PREFIX/arm-linux-gnueabi/4.9.2/cc1"
+          
+          ln -sf \
+            "$GCC_EXEC_PREFIX/libexec/gcc/arm-linux-gnueabi/4.9.2/cc1plus" \
+            "$GCC_EXEC_PREFIX/arm-linux-gnueabi/4.9.2/cc1plus"
+
 
 
           if [[ ! -f "$GCC_BIN" ]]; then
